version: '3.1'

services:

#-------------- MARIADB -------------#
    mariadb:
        build:
            context: ./requirements/mariadb/.
        container_name: "mariadb"
        image: "mariadb:0.2"
        init: true
        restart: on-failure
        volumes:
            - $MDB_VOLUME:/var/lib/mysql
        env_file:
            - .env
        networks:
            - backend

#------------- WORDPRESS ------------#
    wordpress:
        build:
            context: ./requirements/wordpress/.
        container_name: "wordpress"
        image: "wordpress:0.1"
        init: true
        depends_on:
            - mariadb
        restart: on-failure
        env_file:
            - .env
        volumes:
            - $WP_VOLUME:/var/www/html
            - $MDB_VOLUME:/run/mysqld
        networks:
            - frontend
            - backend

#--------------- NGINX --------------#
    nginx:
        build:
            context: ./requirements/nginx/.
        container_name: "nginx"
        image: "nginx:0.2"
        init: true
        depends_on:
            - wordpress
        restart: on-failure
        env_file:
            - .env
        ports:
            - "443:443"
        volumes:
            - $WP_VOLUME:/var/www/html
        networks:
            - frontend

# #--------------- NETWORKS --------------#

networks:
    frontend:
    backend:

# #--------------- VOLUMES --------------#

volumes:
        mariadb_data:
            driver_opts:
                type: none
                device: /home/dpaccagn/data/mysql
                o: bind
        wordpress_data:
            driver_opts:
                type: none
                device: /home/dpaccagn/data/wordpress
                o: bind
