version: '3.1'

services:

#-------------- MARIADB -------------#
    mariadb:
        build:
            context: ./requirements/mariadb/.
        container_name: "mariadb"
        image: "mariadb:0.2"
        init: true
        restart: on-failure
        volumes:
            - $MDB_VOLUME:/var/lib/mysql
        env_file:
            - .env
        networks:
            - backend

#------------- WORDPRESS ------------#
    wordpress:
        build:
            context: ./requirements/wordpress/.
        container_name: "wordpress"
        image: "wordpress:0.1"
        init: true
        depends_on:
            - mariadb
        restart: on-failure
        env_file:
            - .env
        volumes:
            - $WP_VOLUME:/var/www/html
            - $MDB_VOLUME:/run/mysqld
        networks:
            - frontend
            - backend

#--------------- NGINX --------------#
    nginx:
        build:
            context: ./requirements/nginx/.
        container_name: "nginx"
        image: "nginx:0.2"
        init: true
        depends_on:
            - wordpress
        restart: on-failure
        env_file:
            - .env
        ports:
            - "443:443"
        volumes:
            - $WP_VOLUME:/var/www/html
        networks:
            - frontend

#--------------- VSFTPD --------------#
    vsftpd:
        build:
            context: ./requirements/vsftpd/.
        container_name: "vsftpd"
        image: "vsftpd:3.0"
        init: true
        depends_on:
            - nginx
        restart: on-failure
        env_file:
            - .env
        ports:
            - "21:21"
            - "21000-21010:21000-21010"
        volumes:
            - $WP_VOLUME:/home/dpaccagn
        networks:
            - backend

#--------------- CHATBOT --------------#
    chatbot:
        build:
            context: ./requirements/chatbot/.
        container_name: "chatbot"
        init: true
        depends_on:
            - nginx
        restart: on-failure
        env_file:
            - .env
        ports:
            - "9500:9500"
        volumes:
            - $CHATBOT_VOLUME
        networks:
            - backend

#--------------- NETWORKS --------------#

networks:
    frontend:
    backend:

#--------------- VOLUMES --------------#

volumes:
        mariadb_data:
            driver_opts:
                type: none
                device: /home/dpaccagn/data/mysql
                o: bind
        wordpress_data:
            driver_opts:
                type: none
                device: /home/dpaccagn/data/wordpress
                o: bind
        chatbot_data:
            driver_opts:
                type: none
                device: /home/dpaccagn/data/chatbot
                o: bind
